{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "832af538",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'flask'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mflask\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m Flask, jsonify, request\n\u001b[32m      3\u001b[39m app = Flask(\u001b[34m__name__\u001b[39m)\n\u001b[32m      5\u001b[39m \u001b[38;5;28;01mclass\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mGerenciadorTarefas\u001b[39;00m:\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'flask'"
     ]
    }
   ],
   "source": [
    "from flask import Flask, jsonify, request\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "class GerenciadorTarefas:\n",
    "    \"\"\"Gerencia a coleção de tarefas em memória.\"\"\"\n",
    "    def __init__(self):\n",
    "        self.tarefas = []\n",
    "        self.contador_id = 1\n",
    "    \n",
    "    def adicionar_tarefa(self, descricao):\n",
    "        tarefa = {\n",
    "            'id': self.contador_id,\n",
    "            'descricao': descricao,\n",
    "            'concluida': False\n",
    "        }\n",
    "        self.tarefas.append(tarefa)\n",
    "        self.contador_id += 1\n",
    "        return tarefa\n",
    "\n",
    "    def obter_tarefa_por_id(self, tarefa_id):\n",
    "        return next((t for t in self.tarefas if t['id'] == tarefa_id), None)\n",
    "    \n",
    "    def atualizar_tarefa(self, tarefa_id, data):\n",
    "        tarefa = self.obter_tarefa_por_id(tarefa_id)\n",
    "        if tarefa:\n",
    "            if 'descricao' in data:\n",
    "                tarefa['descricao'] = data['descricao']\n",
    "            if 'concluida' in data:\n",
    "                tarefa['concluida'] = data['concluida']\n",
    "            return tarefa\n",
    "        return None\n",
    "\n",
    "    def deletar_tarefa(self, tarefa_id):\n",
    "        tarefa_inicial = len(self.tarefas)\n",
    "        self.tarefas = [t for t in self.tarefas if t['id'] != tarefa_id]\n",
    "        return len(self.tarefas) != tarefa_inicial # Retorna True se a tarefa foi removida\n",
    "\n",
    "gerenciador = GerenciadorTarefas()\n",
    "\n",
    "# --- Rotas da API (CRUD) ---\n",
    "\n",
    "@app.route('/tarefas', methods=['GET'])\n",
    "def obter_tarefas():\n",
    "    \"\"\"Retorna todas as tarefas.\"\"\"\n",
    "    return jsonify(gerenciador.tarefas)\n",
    "\n",
    "@app.route('/tarefas', methods=['POST'])\n",
    "def criar_tarefa():\n",
    "    \"\"\"Cria uma nova tarefa. Requer JSON: {'descricao': '...'}\"\"\"\n",
    "    if not request.json or 'descricao' not in request.json:\n",
    "        return jsonify({'erro': 'Descricao é obrigatória'}), 400\n",
    "        \n",
    "    descricao = request.json.get('descricao')\n",
    "    tarefa = gerenciador.adicionar_tarefa(descricao)\n",
    "    return jsonify(tarefa), 201\n",
    "\n",
    "@app.route('/tarefas/<int:tarefa_id>', methods=['GET'])\n",
    "def obter_tarefa(tarefa_id):\n",
    "    \"\"\"Obtém uma tarefa específica pelo ID.\"\"\"\n",
    "    tarefa = gerenciador.obter_tarefa_por_id(tarefa_id)\n",
    "    if not tarefa:\n",
    "        return jsonify({'erro': 'Tarefa não encontrada'}), 404\n",
    "    return jsonify(tarefa)\n",
    "\n",
    "\n",
    "@app.route('/tarefas/<int:tarefa_id>', methods=['PUT'])\n",
    "def atualizar_tarefa(tarefa_id):\n",
    "    \"\"\"Atualiza uma tarefa existente. Requer JSON: {'descricao': '...' e/ou 'concluida': True/False}\"\"\"\n",
    "    if not request.json:\n",
    "        return jsonify({'erro': 'Dados de atualização ausentes'}), 400\n",
    "        \n",
    "    tarefa_atualizada = gerenciador.atualizar_tarefa(tarefa_id, request.json)\n",
    "    if not tarefa_atualizada:\n",
    "        return jsonify({'erro': 'Tarefa não encontrada'}), 404\n",
    "        \n",
    "    return jsonify(tarefa_atualizada)\n",
    "\n",
    "@app.route('/tarefas/<int:tarefa_id>', methods=['DELETE'])\n",
    "def deletar_tarefa(tarefa_id):\n",
    "    \"\"\"Deleta uma tarefa pelo ID.\"\"\"\n",
    "    if gerenciador.deletar_tarefa(tarefa_id):\n",
    "        return jsonify({'mensagem': f'Tarefa {tarefa_id} deletada com sucesso'}), 204 # No Content\n",
    "    return jsonify({'erro': 'Tarefa não encontrada'}), 404\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    # Para rodar localmente: flask run\n",
    "    # Adicionando algumas tarefas iniciais para teste\n",
    "    gerenciador.adicionar_tarefa(\"Configurar o ambiente Flask\")\n",
    "    gerenciador.adicionar_tarefa(\"Implementar rotas GET e POST\")\n",
    "    app.run(debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
